import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'it' | 'en';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  ru: {
    nav_brand: 'Наталия Егорова',
    nav_subtext: 'art · painting · design',
    nav_formats: 'Форматы',
    nav_portfolio: 'Портфолио',
    nav_prices: 'Цены',
    nav_process: 'Как всё проходит',
    nav_contacts: 'Контакты',
    header_location: 'USA / Italy · RU / IT / EN',
    header_cta: 'Написать в Instagram',
    hero_pill: '30+ лет опыта · Россия · Италия · США',
    hero_title_1: 'Красота и гармония,',
    hero_title_2: 'созданные специально для вас',
    hero_subtitle: 'Я **художник-живописец и профессиональная швея**. Создаю **картины, портреты, настенные росписи, роспись мебели и посуды**, а также **шью одежду на заказ**. Каждая работа — **что-то особенное, сделанное именно для вас**.',
    hero_b1: '**30+ лет** творческого опыта в России, Италии и США',
    hero_b2: 'основной фокус — **живопись, портреты и настенные росписи**',
    hero_b3: '**индивидуальный подход** и ручная работа',
    hero_b4: 'общение на **русском, итальянском и английском**',
    hero_b5: '**функциональные и долговечные** материалы',
    hero_cta1: 'Заказать личный проект',
    hero_cta2: 'Посмотреть портфолио',
    hero_note: 'Я работаю с частными заказчиками по всему миру: онлайн-продакшн, общение на русском, итальянском и английском, детальное сопровождение и заботливая упаковка каждой работы.',
    about_label: 'обо мне',
    about_title: 'Познакомимся поближе',
    about_name: 'Natalia Egorova',
    about_subtitle: 'Художник-живописец · Профессиональная швея-модельер',
    about_p1: '**Меня зовут Наталия Егорова** — **художник-живописец и профессиональная швея-модельер** с **30+ лет опыта**. Родилась в России, жила в Италии, сейчас в США. Создала **более 100 произведений** живописи и множество коллекций одежды.',
    about_p2: 'Специализируюсь на **живописи, портретах, настенных росписях, росписи мебели и посуды**. Также **шью одежду на заказ** — платья, костюмы, пальто.',
    about_p3: 'Моя философия: когда человек прикасается к моей работе, он должен почувствовать **радость от соприкосновения с красивым и гармоничным** — будто он держит в руках **не просто вещь, а что-то особенное, сделанное именно для него**. Каждая деталь продумана, каждый стежок выполнен с любовью. Я работаю онлайн с заказчиками по всему миру, общаюсь на **русском и итальянском свободно**, английский изучаю, и всегда готова поддержать вас на каждом этапе.',
    about_p4: '**20 лет я прожила на юге Италии**, рядом с Амальфитанским побережьем, и вдохновлялась его **невероятной красотой, яркими красками, изысканной кухней, теплотой счастливых и приветливых людей** и **прекрасной уникальной природой**. Эта атмосфера навсегда вошла в мои работы.',
    about_why_title: 'Почему выбирают меня?',
    about_why1: '**Глубина и внимание к деталям** — каждая работа создается вручную с искренностью и уважением к вашей истории',
    about_why2: '**Гармония формы, цвета и содержания** — соединяю эстетику с функциональностью, чтобы вещи служили долго',
    about_why3: '**Индивидуальный подход** — каждый заказ уникален, мы найдём то, что подходит именно вам',
    about_stat1: 'лет опыта',
    about_stat2: 'завершённых проектов',
    about_stat4: 'любовь к каждой детали',
    f_label: 'форматы работ',
    f_title: 'Что я создаю',
    f_subtitle: 'От портретов до интерьеров — каждая работа создаётся вручную',
    f_card1_title: 'Портреты',
    f_card1_text: 'Индивидуальные портреты — холст, акрил, масло. От классики до современных стилей.',
    f_card1_tag: 'живопись',
    f_card2_title: 'Настенные росписи',
    f_card2_text: 'Уникальные росписи стен — от детских комнат до ресторанов.',
    f_card2_tag: 'интерьер',
    f_card3_title: 'Роспись мебели',
    f_card3_text: 'Декоративная роспись мебели — столы, комоды, шкафы.',
    f_card3_tag: 'декор',
    f_card4_title: 'Роспись посуды',
    f_card4_text: 'Художественная роспись посуды — тарелки, чашки, вазы.',
    f_card4_tag: 'керамика',
    f_card5_title: 'Картины на заказ',
    f_card5_text: 'Индивидуальные картины любого размера и стиля.',
    f_card5_tag: 'живопись',
    f_card6_title: 'Одежда на заказ',
    f_card6_text: 'Шью платья, костюмы, пальто — от эскиза до готового изделия.',
    f_card6_tag: 'fashion',
    f_card7_title: 'Эскизы',
    f_card7_text: 'Художественные эскизы и наброски для любых целей.',
    f_card7_tag: 'графика',
    f_card8_title: 'Консультации',
    f_card8_text: 'Помогу подобрать стиль, цвета и концепцию вашего проекта.',
    f_card8_tag: 'консалтинг',
    price_label: 'цены',
    price_title: 'Прозрачно обсуждаем бюджет до начала работы',
    price_subtitle: 'Каждый проект уникален, поэтому итоговая стоимость зависит от формата, размера, используемых материалов и сроков.',
    p_card1_badge: 'портреты',
    p_card1_title: '1 человек',
    p_card1_l1: 'Холст, акрил/масло',
    p_card1_l2: 'От 50×60 см',
    p_card1_l3: 'Срок: 2-4 недели',
    p_card1_note: 'от $300',
    p_card2_badge: 'настенные росписи',
    p_card2_title: 'за м²',
    p_card2_l1: 'Эскиз включён',
    p_card2_l2: 'Подготовка поверхности',
    p_card2_l3: 'Работа на месте',
    p_card2_note: 'от $150/м²',
    p_card3_badge: 'одежда',
    p_card3_title: 'платье/костюм',
    p_card3_l1: 'От эскиза до изделия',
    p_card3_l2: 'Примерки включены',
    p_card3_l3: 'Индивидуальный пошив',
    p_card3_note: 'от $400',
    p_gift_title: 'Подарочные сертификаты',
    p_gift_text: 'Подарите близким возможность получить уникальное произведение искусства. Сертификаты любого номинала.',
    p_gift_cta: 'Заказать сертификат',
    why_label: 'преимущества',
    why_title: 'Почему выбирают меня',
    why_subtitle: 'Что делает мои работы особенными',
    w_card1_title: 'Опыт 30+ лет',
    w_card1_text: 'Профессиональное образование и десятилетия практики в России, Италии и США.',
    w_card2_title: 'Ручная работа',
    w_card2_text: 'Каждая деталь создаётся вручную с любовью и вниманием.',
    w_card3_title: 'Онлайн сопровождение',
    w_card3_text: 'Работаю с клиентами по всему миру, полное сопровождение онлайн.',
    w_card4_title: 'Индивидуальный подход',
    w_card4_text: 'Каждый проект уникален, учитываю все ваши пожелания.',
    w_card5_title: 'Качественные материалы',
    w_card5_text: 'Использую только проверенные краски, холсты и ткани.',
    w_card6_title: '3 языка',
    w_card6_text: 'Общаюсь на русском, итальянском и английском.',
    process_label: 'процесс',
    process_title: 'Как всё проходит',
    process_subtitle: 'От первой встречи до готового произведения',
    step1_title: 'Знакомство',
    step1_text: 'Обсуждаем ваши идеи, пожелания, бюджет и сроки.',
    step2_title: 'Эскиз',
    step2_text: 'Создаю эскиз или концепт, согласовываем детали.',
    step3_title: 'Работа',
    step3_text: 'Воплощаю проект в жизнь, показываю процесс.',
    step4_title: 'Доставка',
    step4_text: 'Упаковываю работу и отправляю вам или монтирую на месте.',
    port_label: 'портфолио',
    port_title: 'Мои работы',
    port_subtitle: 'Примеры завершённых проектов',
    port_cap1: 'Семейный портрет, холст 80×100 см',
    port_cap2: 'Вечернее платье на заказ',
    port_cap3: 'Роспись винтажного комода',
    port_cap4: 'Коллекция платьев',
    port_cap5: 'Портрет маслом',
    port_cap6: 'Настенная роспись в помещениях',
    contacts_label: 'если остались вопросы',
    contacts_title: 'Давайте обсудим ваш будущий проект',
    write_me: 'НАПИШИТЕ МНЕ',
    request_format: 'ФОРМАТ ЗАЯВКИ',
    request_format_text: 'Кратко опишите, что вы хотите: картину, одежду, реставрацию или другое. Добавьте пару слов о человеке или пространстве, для которого создаётся работа.',
    faq1_title: 'С какой страной вы работаете',
    faq1_text: 'Я нахожусь в США, имею длительный опыт работы в Италии и России и принимаю заказы со всего мира. Мы обсуждаем задачу онлайн, а готовые работы отправляю надежными службами доставки.',
    faq2_title: 'Что, если я плохо понимаю, чего хочу',
    faq2_text: 'Это нормально. Я аккуратно задаю вопросы, предлагаю варианты, показываю примеры и помогаю сформулировать, какая вещь или картина реально сделает вашу жизнь красивее и удобнее.',
    faq3_title: 'Можно ли сделать подарок-сюрприз',
    faq3_text: 'Да. Мы можем создать тайный проект по фото и описанию или оформить подарочный сертификат, чтобы человек сам выбрал формат. Я подскажу, что лучше сработает в вашей ситуации.',
    faq4_title: 'На каком языке мы будем общаться',
    faq4_text: 'Свободно говорю по-русски и по-итальянски, уверенно общаюсь на английском. Главное — ваше желание делиться мечтой, а я помогу перевести её на язык формы, цвета и ткани.',
    name_placeholder: 'Ваше имя',
    email_placeholder: 'Ваш e-mail',
    message_placeholder: 'Расскажите немного о вашем запросе',
    send_button: 'Отправить запрос',
    hero_card1_tag: 'живопись',
    hero_card1_title: 'Портреты',
    hero_card1_text: 'Индивидуальные портреты маслом и акрилом',
    hero_card1_offer: 'от $300',
    hero_card2_tag: 'fashion',
    hero_card2_title: 'Одежда на заказ',
    hero_card2_text: 'Платья, костюмы, пальто ручной работы',
    hero_card3_tag: 'интерьер',
    hero_card3_title: 'Настенные росписи',
    hero_card3_text: 'Уникальный декор для вашего дома',
    hero_card4_tag: 'декор',
    hero_card4_title: 'Роспись',
    hero_card4_text: 'Роспись мебели и посуды',
    footer_copy: 'Художник и швея-модельер с более 30 лет опыта',
  },
  it: {
    nav_brand: 'Natalia Egorova',
    nav_subtext: 'arte · pittura · design',
    nav_formats: 'Formati',
    nav_portfolio: 'Portfolio',
    nav_prices: 'Prezzi',
    nav_process: 'Come funziona',
    nav_contacts: 'Contatti',
    header_location: 'USA / Italia · RU / IT / EN',
    header_cta: 'Scrivimi su Instagram',
    hero_pill: '30+ anni di esperienza · Russia · Italia · USA',
    hero_title_1: 'Bellezza e armonia,',
    hero_title_2: 'create appositamente per te',
    hero_subtitle: 'Sono **pittrice e sarta professionista**. Creo **dipinti, ritratti, murales, decorazioni su mobili e ceramiche**, oltre a **cucire abiti su misura**. Ogni lavoro è **qualcosa di speciale, fatto appositamente per te**.',
    hero_b1: '**30+ anni** di esperienza creativa in Russia, Italia e USA',
    hero_b2: 'focus principale — **pittura, ritratti e murales**',
    hero_b3: '**approccio individuale** e lavoro artigianale',
    hero_b4: 'comunico in **russo, italiano e inglese**',
    hero_b5: 'materiali **funzionali e durevoli**',
    hero_cta1: 'Ordina un progetto personale',
    hero_cta2: 'Guarda il portfolio',
    hero_note: 'Lavoro con clienti privati in tutto il mondo: produzione online, comunicazione in russo, italiano e inglese, assistenza dettagliata e imballaggio accurato di ogni lavoro.',
    about_label: 'chi sono',
    about_title: 'Conosciamoci meglio',
    about_name: 'Natalia Egorova',
    about_subtitle: 'Pittrice · Sarta-modellista professionista',
    about_p1: '**Mi chiamo Natalia Egorova** — **pittrice e sarta-modellista professionista** con **30+ anni di esperienza**. Nata in Russia, ho vissuto in Italia, ora negli USA. Ho creato **oltre 100 opere** di pittura e numerose collezioni di abbigliamento.',
    about_p2: 'Mi specializzo in **pittura, ritratti, murales, decorazione di mobili e ceramiche**. Realizzo anche **abiti su misura** — vestiti, costumi, cappotti.',
    about_p3: 'La mia filosofia: quando una persona tocca il mio lavoro, deve sentire **la gioia di entrare in contatto con qualcosa di bello e armonioso** — come se tenesse in mano **non solo un oggetto, ma qualcosa di speciale, fatto appositamente per lui**. Ogni dettaglio è pensato, ogni punto fatto con amore. Lavoro online con clienti in tutto il mondo, parlo **russo e italiano fluentemente**, sto imparando l\'inglese e sono sempre pronta a sostenervi in ogni fase.',
    about_p4: '**Ho vissuto 20 anni nel sud Italia**, vicino alla Costiera Amalfitana, e mi sono ispirata alla sua **bellezza incredibile, ai colori vivaci, alla cucina raffinata, al calore delle persone felici e accoglienti** e alla **meravigliosa natura unica**. Questa atmosfera è entrata per sempre nelle mie opere.',
    about_why_title: 'Perché scegliermi?',
    about_why1: '**Profondità e attenzione ai dettagli** — ogni lavoro è creato a mano con sincerità e rispetto per la tua storia',
    about_why2: '**Armonia di forma, colore e contenuto** — unisco estetica e funzionalità perché le cose durino a lungo',
    about_why3: '**Approccio individuale** — ogni ordine è unico, troveremo quello che fa per te',
    about_stat1: 'anni di esperienza',
    about_stat2: 'progetti completati',
    about_stat4: 'amore per ogni dettaglio',
    f_label: 'formati di lavoro',
    f_title: 'Cosa creo',
    f_subtitle: 'Dai ritratti agli interni — ogni lavoro è creato a mano',
    f_card1_title: 'Ritratti',
    f_card1_text: 'Ritratti individuali — tela, acrilico, olio. Da classico a moderno.',
    f_card1_tag: 'pittura',
    f_card2_title: 'Murales',
    f_card2_text: 'Murales unici — da camerette a ristoranti.',
    f_card2_tag: 'interni',
    f_card3_title: 'Decorazione mobili',
    f_card3_text: 'Decorazione artistica di mobili — tavoli, cassettiere, armadi.',
    f_card3_tag: 'decor',
    f_card4_title: 'Decorazione ceramiche',
    f_card4_text: 'Decorazione artistica di ceramiche — piatti, tazze, vasi.',
    f_card4_tag: 'ceramica',
    f_card5_title: 'Dipinti su commissione',
    f_card5_text: 'Dipinti individuali di qualsiasi dimensione e stile.',
    f_card5_tag: 'pittura',
    f_card6_title: 'Abiti su misura',
    f_card6_text: 'Cucio vestiti, costumi, cappotti — dal disegno al prodotto finito.',
    f_card6_tag: 'moda',
    f_card7_title: 'Schizzi',
    f_card7_text: 'Schizzi artistici e bozzetti per qualsiasi scopo.',
    f_card7_tag: 'grafica',
    f_card8_title: 'Consulenze',
    f_card8_text: 'Ti aiuto a scegliere stile, colori e concept del tuo progetto.',
    f_card8_tag: 'consulenza',
    price_label: 'prezzi',
    price_title: 'Discutiamo il budget in modo trasparente prima di iniziare',
    price_subtitle: 'Ogni progetto è unico, quindi il costo finale dipende dal formato, dalle dimensioni, dai materiali utilizzati e dai tempi.',
    p_card1_badge: 'ritratti',
    p_card1_title: '1 persona',
    p_card1_l1: 'Tela, acrilico/olio',
    p_card1_l2: 'Da 50×60 cm',
    p_card1_l3: 'Tempo: 2-4 settimane',
    p_card1_note: 'da $300',
    p_card2_badge: 'murales',
    p_card2_title: 'al m²',
    p_card2_l1: 'Bozzetto incluso',
    p_card2_l2: 'Preparazione superficie',
    p_card2_l3: 'Lavoro in loco',
    p_card2_note: 'da $150/m²',
    p_card3_badge: 'abbigliamento',
    p_card3_title: 'vestito/costume',
    p_card3_l1: 'Dal disegno al prodotto',
    p_card3_l2: 'Prove incluse',
    p_card3_l3: 'Sartoria individuale',
    p_card3_note: 'da $400',
    p_gift_title: 'Buoni regalo',
    p_gift_text: 'Regala ai tuoi cari la possibilità di ricevere un\'opera d\'arte unica. Buoni di qualsiasi importo.',
    p_gift_cta: 'Ordina buono',
    why_label: 'vantaggi',
    why_title: 'Perché scegliermi',
    why_subtitle: 'Cosa rende speciali i miei lavori',
    w_card1_title: 'Esperienza 30+ anni',
    w_card1_text: 'Formazione professionale e decenni di pratica in Russia, Italia e USA.',
    w_card2_title: 'Fatto a mano',
    w_card2_text: 'Ogni dettaglio è creato a mano con amore e attenzione.',
    w_card3_title: 'Assistenza online',
    w_card3_text: 'Lavoro con clienti in tutto il mondo, assistenza completa online.',
    w_card4_title: 'Approccio individuale',
    w_card4_text: 'Ogni progetto è unico, tengo conto di tutti i tuoi desideri.',
    w_card5_title: 'Materiali di qualità',
    w_card5_text: 'Uso solo colori, tele e tessuti testati.',
    w_card6_title: '3 lingue',
    w_card6_text: 'Comunico in russo, italiano e inglese.',
    process_label: 'processo',
    process_title: 'Come funziona',
    process_subtitle: 'Dal primo incontro all\'opera finita',
    step1_title: 'Conoscenza',
    step1_text: 'Discutiamo le tue idee, desideri, budget e tempi.',
    step2_title: 'Bozzetto',
    step2_text: 'Creo un bozzetto o concept, accordiamo i dettagli.',
    step3_title: 'Lavoro',
    step3_text: 'Realizzo il progetto, mostro il processo.',
    step4_title: 'Consegna',
    step4_text: 'Imballo il lavoro e te lo spedisco o lo installo in loco.',
    port_label: 'portfolio',
    port_title: 'I miei lavori',
    port_subtitle: 'Esempi di progetti completati',
    port_cap1: 'Ritratto di famiglia, tela 80×100 cm',
    port_cap2: 'Abito da sera su misura',
    port_cap3: 'Decorazione cassettiera vintage',
    port_cap4: 'Collezione di vestiti',
    port_cap5: 'Ritratto a olio',
    port_cap6: 'Murale negli interni',
    contacts_label: 'se ci sono domande',
    contacts_title: 'Discutiamo il tuo progetto futuro',
    write_me: 'SCRIVIMI',
    request_format: 'FORMATO RICHIESTA',
    request_format_text: 'Descrivi brevemente cosa vuoi: un dipinto, abbigliamento, restauro o altro. Aggiungi un paio di parole sulla persona o lo spazio per cui viene creato il lavoro.',
    faq1_title: 'Con quale paese lavori',
    faq1_text: 'Mi trovo negli Stati Uniti, ho una lunga esperienza di lavoro in Italia e Russia e accetto ordini da tutto il mondo. Discutiamo il compito online e invio i lavori finiti tramite servizi di consegna affidabili.',
    faq2_title: 'E se non capisco bene cosa voglio',
    faq2_text: 'È normale. Faccio domande con attenzione, suggerisco opzioni, mostro esempi e aiuto a formulare quale oggetto o dipinto renderà davvero la tua vita più bella e comoda.',
    faq3_title: 'Si può fare un regalo a sorpresa',
    faq3_text: 'Sì. Possiamo creare un progetto segreto basato su foto e descrizione o creare un certificato regalo in modo che la persona possa scegliere il formato da sola. Ti dirò cosa funziona meglio nella tua situazione.',
    faq4_title: 'In che lingua comunicheremo',
    faq4_text: 'Parlo fluentemente russo e italiano, comunico con sicurezza in inglese. La cosa principale è il tuo desiderio di condividere il tuo sogno, e io aiuterò a tradurlo nel linguaggio della forma, del colore e del tessuto.',
    name_placeholder: 'Il tuo nome',
    email_placeholder: 'La tua e-mail',
    message_placeholder: 'Raccontami un po\' della tua richiesta',
    send_button: 'Invia richiesta',
    hero_card1_tag: 'pittura',
    hero_card1_title: 'Ritratti',
    hero_card1_text: 'Ritratti individuali a olio e acrilico',
    hero_card1_offer: 'da $300',
    hero_card2_tag: 'moda',
    hero_card2_title: 'Abiti su misura',
    hero_card2_text: 'Vestiti, costumi, cappotti fatti a mano',
    hero_card3_tag: 'interni',
    hero_card3_title: 'Murales',
    hero_card3_text: 'Decorazione unica per la tua casa',
    hero_card4_tag: 'decor',
    hero_card4_title: 'Decorazioni',
    hero_card4_text: 'Decorazione di mobili e ceramiche',
    footer_copy: 'Pittrice e sarta-modellista con più di 30 anni di esperienza',
  },
  en: {
    nav_brand: 'Natalia Egorova',
    nav_subtext: 'art · painting · design',
    nav_formats: 'Formats',
    nav_portfolio: 'Portfolio',
    nav_prices: 'Pricing',
    nav_process: 'How it works',
    nav_contacts: 'Contact',
    header_location: 'USA / Italy · RU / IT / EN',
    header_cta: 'Message on Instagram',
    hero_pill: '30+ years experience · Russia · Italy · USA',
    hero_title_1: 'Beauty and harmony,',
    hero_title_2: 'created especially for you',
    hero_subtitle: 'I\'m a **professional painter and seamstress**. I create **paintings, portraits, murals, furniture and pottery decorations**, and **sew custom clothing**. Every piece is **something special, made just for you**.',
    hero_b1: '**30+ years** of creative experience in Russia, Italy, and USA',
    hero_b2: 'main focus — **painting, portraits, and murals**',
    hero_b3: '**individual approach** and handmade work',
    hero_b4: 'communicate in **Russian, Italian, and English**',
    hero_b5: '**functional and durable** materials',
    hero_cta1: 'Order a personal project',
    hero_cta2: 'View portfolio',
    hero_note: 'I work with private clients worldwide: online production, communication in Russian, Italian, and English, detailed support, and careful packaging of every piece.',
    about_label: 'about me',
    about_title: 'Let\'s get acquainted',
    about_name: 'Natalia Egorova',
    about_subtitle: 'Painter · Professional Fashion Designer & Seamstress',
    about_p1: '**My name is Natalia Egorova** — **professional painter and fashion designer & seamstress** with **30+ years of experience**. Born in Russia, lived in Italy, now in the USA. Created **over 100 paintings** and numerous clothing collections.',
    about_p2: 'I specialize in **painting, portraits, murals, furniture and pottery decoration**. I also **sew custom clothing** — dresses, suits, coats.',
    about_p3: 'My philosophy: when someone touches my work, they should feel **the joy of connecting with something beautiful and harmonious** — as if holding **not just an object, but something special, made just for them**. Every detail is thought through, every stitch made with love. I work online with clients worldwide, speak **Russian and Italian fluently**, learning English, and always ready to support you at every stage.',
    about_p4: '**I lived 20 years in southern Italy**, near the Amalfi Coast, and was inspired by its **incredible beauty, vibrant colors, exquisite cuisine, the warmth of happy and welcoming people**, and **wonderful unique nature**. This atmosphere has forever entered my works.',
    about_why_title: 'Why choose me?',
    about_why1: '**Depth and attention to detail** — every piece is handmade with sincerity and respect for your story',
    about_why2: '**Harmony of form, color, and content** — I combine aesthetics with functionality so things last',
    about_why3: '**Individual approach** — every order is unique, we\'ll find what suits you',
    about_stat1: 'years experience',
    about_stat2: 'completed projects',
    about_stat4: 'love for every detail',
    f_label: 'work formats',
    f_title: 'What I create',
    f_subtitle: 'From portraits to interiors — every piece is handmade',
    f_card1_title: 'Portraits',
    f_card1_text: 'Individual portraits — canvas, acrylic, oil. From classic to modern styles.',
    f_card1_tag: 'painting',
    f_card2_title: 'Murals',
    f_card2_text: 'Unique wall paintings — from kids\' rooms to restaurants.',
    f_card2_tag: 'interior',
    f_card3_title: 'Furniture decoration',
    f_card3_text: 'Decorative furniture painting — tables, dressers, cabinets.',
    f_card3_tag: 'decor',
    f_card4_title: 'Pottery decoration',
    f_card4_text: 'Artistic pottery decoration — plates, cups, vases.',
    f_card4_tag: 'ceramics',
    f_card5_title: 'Custom paintings',
    f_card5_text: 'Individual paintings of any size and style.',
    f_card5_tag: 'painting',
    f_card6_title: 'Custom clothing',
    f_card6_text: 'I sew dresses, suits, coats — from sketch to finished product.',
    f_card6_tag: 'fashion',
    f_card7_title: 'Sketches',
    f_card7_text: 'Artistic sketches and drafts for any purpose.',
    f_card7_tag: 'graphics',
    f_card8_title: 'Consultations',
    f_card8_text: 'I\'ll help you choose style, colors, and concept for your project.',
    f_card8_tag: 'consulting',
    price_label: 'pricing',
    price_title: 'We discuss the budget transparently before starting',
    price_subtitle: 'Each project is unique, so the final cost depends on format, size, materials used, and timeline.',
    p_card1_badge: 'portraits',
    p_card1_title: '1 person',
    p_card1_l1: 'Canvas, acrylic/oil',
    p_card1_l2: 'From 50×60 cm',
    p_card1_l3: 'Time: 2-4 weeks',
    p_card1_note: 'from $300',
    p_card2_badge: 'murals',
    p_card2_title: 'per m²',
    p_card2_l1: 'Sketch included',
    p_card2_l2: 'Surface preparation',
    p_card2_l3: 'On-site work',
    p_card2_note: 'from $150/m²',
    p_card3_badge: 'clothing',
    p_card3_title: 'dress/suit',
    p_card3_l1: 'From sketch to product',
    p_card3_l2: 'Fittings included',
    p_card3_l3: 'Individual tailoring',
    p_card3_note: 'from $400',
    p_gift_title: 'Gift certificates',
    p_gift_text: 'Give your loved ones the opportunity to receive a unique work of art. Certificates of any amount.',
    p_gift_cta: 'Order certificate',
    why_label: 'advantages',
    why_title: 'Why choose me',
    why_subtitle: 'What makes my work special',
    w_card1_title: '30+ years experience',
    w_card1_text: 'Professional education and decades of practice in Russia, Italy, and USA.',
    w_card2_title: 'Handmade',
    w_card2_text: 'Every detail is handmade with love and attention.',
    w_card3_title: 'Online support',
    w_card3_text: 'I work with clients worldwide, full online support.',
    w_card4_title: 'Individual approach',
    w_card4_text: 'Every project is unique, I consider all your wishes.',
    w_card5_title: 'Quality materials',
    w_card5_text: 'I use only tested paints, canvases, and fabrics.',
    w_card6_title: '3 languages',
    w_card6_text: 'I communicate in Russian, Italian, and English.',
    process_label: 'process',
    process_title: 'How it works',
    process_subtitle: 'From first meeting to finished piece',
    step1_title: 'Meeting',
    step1_text: 'We discuss your ideas, wishes, budget, and timeline.',
    step2_title: 'Sketch',
    step2_text: 'I create a sketch or concept, we agree on details.',
    step3_title: 'Work',
    step3_text: 'I bring the project to life, show the process.',
    step4_title: 'Delivery',
    step4_text: 'I pack the work and ship it to you or install it on-site.',
    port_label: 'portfolio',
    port_title: 'My works',
    port_subtitle: 'Examples of completed projects',
    port_cap1: 'Family portrait, canvas 80×100 cm',
    port_cap2: 'Custom evening dress',
    port_cap3: 'Vintage dresser decoration',
    port_cap4: 'Dress collection',
    port_cap5: 'Oil portrait',
    port_cap6: 'Mural in interior spaces',
    contacts_label: 'if you have questions',
    contacts_title: "Let's discuss your future project",
    write_me: 'WRITE TO ME',
    request_format: 'REQUEST FORMAT',
    request_format_text: 'Briefly describe what you want: a painting, clothes, restoration or something else. Add a couple of words about a person or space for which the work is being created.',
    faq1_title: 'Which country do you work with',
    faq1_text: 'I am based in the USA, have extensive experience working in Italy and Russia, and accept orders from all over the world. We discuss the task online, and I send the finished work by reliable delivery services.',
    faq2_title: 'What if I don\'t understand what I want',
    faq2_text: 'This is normal. I carefully ask questions, suggest options, show examples and help to formulate what thing or painting will really make your life more beautiful and convenient.',
    faq3_title: 'Can I make a surprise gift',
    faq3_text: 'Yes. We can create a secret project based on a photo and description or create a gift certificate so that the person can choose the format themselves. I\'ll tell you what works best in your situation.',
    faq4_title: 'What language will we communicate in',
    faq4_text: 'I speak Russian and Italian fluently, I\'m sure I can speak English. The main thing is your desire to share your dream, and I will help translate it into the language of form, color and fabric.',
    name_placeholder: 'Your name',
    email_placeholder: 'Your e-mail',
    message_placeholder: 'Tell me a little about your request',
    send_button: 'Send request',
    hero_card1_tag: 'painting',
    hero_card1_title: 'Portraits',
    hero_card1_text: 'Individual oil and acrylic portraits',
    hero_card1_offer: 'from $300',
    hero_card2_tag: 'fashion',
    hero_card2_title: 'Custom clothing',
    hero_card2_text: 'Handmade dresses, suits, coats',
    hero_card3_tag: 'interior',
    hero_card3_title: 'Murals',
    hero_card3_text: 'Unique decor for your home',
    hero_card4_tag: 'decor',
    hero_card4_title: 'Decoration',
    hero_card4_text: 'Furniture and pottery decoration',
    footer_copy: 'Painter and fashion designer with over 30 years experience',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
